version: '2'

services:
  php:
    image: prooph/php:7.2-cli
    volumes:
      - .:/app
    environment:
      - PROOPH_ENV=dev
      - PDO_DSN=pgsql:host=postgres port=5433 dbname=event_engine
      - PDO_USER=postgres
      - PDO_PWD=

  postgres:
    image: postgres:alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=event_engine
